Base de datos 'proyecto_bd' abierta/creada con Ã©xito
1970-01-01 04:09:14
Traceback (most recent call last):
  File "controller.py", line 14, in <module>
    lista = test.join()
  File "/home/debian-moises/Documentos/securityproject/trunk/version-1-0/source.py", line 207, in join
    self.process()
  File "/home/debian-moises/Documentos/securityproject/trunk/version-1-0/source.py", line 156, in process
    self.dictionary = self.get_log_values(self.result[self.i])
  File "/home/debian-moises/Documentos/securityproject/trunk/version-1-0/source.py", line 89, in get_log_values
    print datetime.datetime(2015, 10, 2, 12, 30)
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
